schema-version: v2
kind: plugin
metadata:
  name: spring-boot-base-plugin
  display-name: spring-boot-base-plugin
  description: Spring Boot + Kotlin Rest API
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: False
  repository: https://github.com/leodelmiro/stackspot-spring-boot-base-plugin.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Kotlin
    - Maven
    - Spring Boot
  stk-projects-only: false
  inputs:
    - label: Type application name
      name: project_name
      type: text
      required: true
      default: Spring Base Project
      help: 'Inform your application name (e.g.: Spring Base Project)'
    - label: Type description
      name: description
      type: text
      required: false
      default: Demo project for Stackspot
      help: 'Inform project description (e.g.: Demo project for Stackspot)'
    - label: Type artifact Id
      name: artifact_id
      type: text
      required: true
      pattern: ^[a-z]([a-z0-9]|_)*$
      default: springbase
      help: 'Inform your maven artifact id. Jar Name. (e.g.: spring-base-project)'
    - label: Type group name
      name: group_name
      type: text
      required: true
      default: br.com.leodelmiro
      help: 'Inform your group name (e.g.: br.com.leodelmiro)'
    - label: Spring Boot Version
      name: springboot_version
      type: text
      default: 3.2.1
      required: true
    - label: Java version
      name: java_version
      type: select
      items:
        - "11"
        - "17"
        - "21"
      default: 17
      required: true    
    - label: Kotlin version
      name: kotlin_version
      type: text
      default: 1.9.22
      required: true
  global-computed-inputs:
    main_class: "{{ project_name | pascalcase }}"
    project_name_lower: "{{ artifact_id | replace('-','') | replace('_','') | lower }}"
    project_base_package: "{{ group_name }}.{{ project_name_lower }}"
    group_name_package: "{{ group_name | group_id_folder }}"
  hooks:
    - type: run
      trigger: after-render
      commands:
        - chmod +x mvnw mvnw.cmd